version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - db
      - selenium
    container_name: app

  db:
    build:
      context: .
      dockerfile: dockerfiles/db/Dockerfile
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: selenium-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - db_data:/var/lib/mysql
    container_name: db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    volumes:
      - ./docker/php-phpmyadmin.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 20080:80
    depends_on:
      - db
    container_name: phpmyadmin

  selenium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900
    container_name: selenium

volumes:
  db_data:
