version: '3.8'

services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900
    container_name: demo_selenium-seleniarm

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - db
      - selenium
    container_name: demo_selenium-app

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: demo_selenium-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    container_name: demo_selenium-db

volumes:
  pgdata:
