# Generated by Django 4.2.9 on 2024-08-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorStandingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructor', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
                ('season', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverStandingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('season', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_prix', models.CharField(max_length=50)),
                ('winner', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=15)),
                ('season', models.IntegerField()),
            ],
        ),
    ]
