# Generated by Django 4.2.9 on 2024-08-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raceresultmodel',
            old_name='time',
            new_name='race_time',
        ),
        migrations.AddField(
            model_name='raceresultmodel',
            name='car',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='raceresultmodel',
            name='laps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raceresultmodel',
            name='race_date',
            field=models.DateField(default=None),
        ),
    ]
