# Generated by Django 4.2.9 on 2024-08-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_time_raceresultmodel_race_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceresultmodel',
            unique_together={('grand_prix', 'season')},
        ),
    ]
