# Generated by Django 4.2.9 on 2024-08-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_raceresultmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceresultmodel',
            unique_together={('grand_prix', 'race_date', 'season')},
        ),
        migrations.AlterModelTable(
            name='constructorstandingmodel',
            table='constructor_standings',
        ),
        migrations.AlterModelTable(
            name='driverstandingmodel',
            table='driver_standings',
        ),
        migrations.AlterModelTable(
            name='raceresultmodel',
            table='race_results',
        ),
    ]
