# Generated by Django 4.2.9 on 2024-09-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_raceresultmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructorstandingmodel',
            name='points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='driverstandingmodel',
            name='points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='driverstandingmodel',
            name='team',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
