name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: selenium-db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rename .env_example to .env
        run: mv .env.github .env

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt

      - name: Apply migrations
        run: |
          python manage.py migrate

      - name: Run tests with pytest
        run: |
          pytest -s -v